server:
  servlet:
    context-path: /api
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_spring_boot_fs
    username: postgres
    password: password
    pool-size: 30
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000